### ISSUE TITLE
java.lang.UnsupportedClassVersionError: com/akamai/edgeauth/EdgeAuthException : Unsupported major.minor version 52.0:

### ISSUE THREAD

**Issue by benbrd** [akamai/EdgeAuth-Token-Java#3]
Documentation is stating that EdgeAuth-Token-Java supports Java 1.6+.
However during testing we got this error when trying to generate the token using edgeauth-0.2.0.jar:
`java.lang.UnsupportedClassVersionError: com/akamai/edgeauth/EdgeAuthException : Unsupported major.minor version 52.0:`

After some research it appears that the 'major.minor version 52.0' error is possibly because the jar was compiled in JDK 1.8, but we are trying to run it using a JDK 1.7 environment. The reported number is the required number, not the number we are using. 

Could you please confirm that Java 1.7 is supported here ? or should we update documentation to indicates that Java 1.8 is required ?

**Comment by mgwoj** [comment]
We are supporting at least Java 8. I hope nowadays it is not a problem.
